export const blogArticles = [
  {
    slug: "efoil-hyeres-voler-sur-eau-sans-vent",
    title: "E-Foil à Hyères : volez au-dessus de l'eau même sans vent",
    excerpt: "Découvrez l'e-foil à Hyères sur la Presqu'île de Giens : sensations de vol au-dessus de l'eau, accessible à tous, même les jours sans vent. KiteSurf Passion depuis 1999.",
    category: "Location",
    date: "2026-07-07",
    readTime: "7 min",
    image: "blog-efoil-hyeres-vol-eau.jpg",
    alt: "E-Foil à Hyères — rider en vol silencieux au-dessus de la Méditerranée, presqu'île de Giens, KiteSurf Passion",
    featured: true,
  },
  {
    slug: "week-end-kitesurf-hyeres-guide-complet",
    title: "Week-end kitesurf à Hyères : le guide complet pour un séjour réussi",
    excerpt: "Tout pour organiser votre week-end kitesurf à Hyères : le spot de l'Almanarre, les conditions de vent, les cours avec KiteSurf Passion et les bons plans du Var.",
    category: "Le Spot",
    date: "2026-06-03",
    readTime: "8 min",
    image: "blog-week-end-kitesurf-hyeres-guide-complet.jpg",
    alt: "Week-end kitesurf à Hyères - Plage de l'Almanarre, presqu'île de Giens, école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "pumpfoil-vs-wingfoil-lequel-choisir-hyeres",
    title: "Pumpfoil vs Wingfoil : Lequel Choisir pour Débuter à Hyères ?",
    excerpt: "Pumpfoil ou wingfoil à Hyères ? Comparatif honnête d'un moniteur diplômé d'État sur l'Almanarre : différences, matériel, apprentissage et conseils pour choisir.",
    category: "Wing Foil",
    date: "2026-06-03",
    readTime: "9 min",
    image: "blog-pumpfoil-vol-sunset-duotone.jpg",
    alt: "Pumpfoil vs wingfoil Hyères - Comparatif débutant Almanarre école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "quelle-aile-choisir-almanarre",
    title: "Quelle taille d'aile de kitesurf choisir à l'Almanarre selon le vent ?",
    excerpt: "Mistral fort ou thermique d'Est régulier : guide pratique pour choisir la bonne taille d'aile de kitesurf à l'Almanarre (Hyères) selon le vent, votre poids, votre niveau et votre support.",
    category: "Le Spot",
    date: "2026-05-30",
    readTime: "7 min",
    image: "blog-kitesurf-ailes-colorees.jpg",
    alt: "Taille d'aile kitesurf Almanarre Hyères - Guide vent poids niveau Kitesurf Passion",
    featured: true,
  },
  {
    slug: "erreurs-debutant-kitesurf-eviter",
    title: "10 Erreurs de Débutant en Kitesurf et Comment les Éviter",
    excerpt: "Découvrez les erreurs les plus fréquentes des débutants en kitesurf et nos conseils d'experts pour les éviter. Progressez plus vite et en toute sécurité.",
    category: "Kitesurf",
    date: "2025-01-12",
    readTime: "7 min",
    image: "blog-kitesurf-eau-claire.jpg",
    alt: "Erreurs débutant kitesurf Hyères - Conseils progression école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "regles-securite-kitesurf-wingfoil",
    title: "Règles de Sécurité Kitesurf et Wingfoil à Hyères : Le Guide Complet",
    excerpt: "Règles de sécurité kitesurf et wingfoil à Hyères : matériel, largage rapide, priorités, distances. Le guide complet par l'école Kitesurf Passion.",
    category: "Sécurité",
    date: "2025-01-08",
    readTime: "8 min",
    image: "blog-bateau-securite-kitesurf-hyeres.jpg",
    alt: "Sécurité kitesurf wingfoil Hyères - Règles navigation école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "guide-equipement-kitesurf-debutant",
    title: "Guide Équipement Kitesurf : Ailes, Planches et Harnais pour Débuter",
    excerpt: "Tout savoir sur le matériel de kitesurf : comment choisir son aile, sa planche et son harnais. Conseils d'experts pour bien s'équiper.",
    category: "Kitesurf",
    date: "2025-01-05",
    readTime: "9 min",
    image: "blog-kitesurf-freestyle-sunset-duotone.jpg",
    alt: "Guide équipement kitesurf débutant - Matériel aile planche harnais Hyères",
  },
  {
    slug: "progression-pumpfoil-debutant-expert",
    title: "Progression Pumpfoil : Du Débutant à l'Expert en 8 Semaines",
    excerpt: "Programme complet pour progresser en pumpfoil. Du dock start aux longues distances, suivez notre méthode éprouvée pour maîtriser le pumping.",
    category: "Pump Foil",
    date: "2025-01-02",
    readTime: "6 min",
    image: "blog-pumpfoil-foil-planche-duotone-strider.jpg",
    alt: "Progression pumpfoil Hyères - Programme entraînement dock start école KiteSurf Passion",
  },
  {
    slug: "debuter-kitesurf-hyeres-guide-complet",
    title: "Débuter le Kitesurf à Hyères : Guide Complet 2026",
    excerpt: "Tout ce que vous devez savoir pour commencer le kitesurf à Hyères. Quel matériel choisir, comment se préparer, et pourquoi l'Almanarre est le spot idéal pour les débutants.",
    category: "Kitesurf",
    date: "2026-02-15",
    readTime: "8 min",
    image: "blog-kitesurf-sunset.jpg",
    alt: "Débuter kitesurf Hyères Almanarre - Guide débutant école KiteSurf Passion Var",
  },
  {
    slug: "wingfoil-sport-tendance-2024",
    title: "Wing Foil : Le Sport de Glisse Tendance en 2026",
    excerpt: "Découvrez pourquoi le wingfoil conquiert la Méditerranée. Plus accessible que le kitesurf, le wingfoil offre des sensations uniques de vol sur l'eau.",
    category: "Wing Foil",
    date: "2026-02-10",
    readTime: "6 min",
    image: "blog-wingfoil-duo-lagon-turquoise.jpg",
    alt: "Wingfoil Hyères tendance 2026 - Stage wing foil école KiteSurf Passion Almanarre",
  },
  {
    slug: "conditions-meteo-almanarre-guide",
    title: "Comprendre les Conditions Météo à l'Almanarre",
    excerpt: "Mistral ou Levant ? Apprenez à décrypter les conditions météo du spot de l'Almanarre pour naviguer dans les meilleures conditions possibles.",
    category: "Le Spot",
    date: "2026-02-05",
    readTime: "5 min",
    image: "blog-kitesurf-backloop-sunset.jpg",
    alt: "Conditions météo kitesurf Almanarre Hyères - Vent Mistral spot Var",
  },
  {
    slug: "pourquoi-bateau-assistance-essentiel",
    title: "Pourquoi un Bateau d'Assistance est Essentiel pour Apprendre",
    excerpt: "L'importance du bateau d'assistance dans l'apprentissage du kitesurf. Sécurité, progression rapide et gain de temps : découvrez tous les avantages.",
    category: "Sécurité",
    date: "2026-01-28",
    readTime: "4 min",
    image: "blog-bateau-securite-kitesurf-hyeres.jpg",
    alt: "Bateau assistance kitesurf Hyères - Sécurité école KiteSurf Passion Var",
  },
  {
    slug: "pumpfoil-dock-start-initiation",
    title: "Pumpfoil & Dock Start : L'Initiation au Foil Sans Vent",
    excerpt: "Pas de vent ? Pas de problème ! Le pumpfoil permet de voler sur l'eau par tous les temps. Découvrez cette discipline accessible à tous.",
    category: "Pump Foil",
    date: "2026-01-20",
    readTime: "5 min",
    image: "blog-pumpfoil-vol-sunset-duotone.jpg",
    alt: "Pumpfoil dock start Hyères Giens - Initiation foil école KiteSurf Passion Var",
  },
  {
    slug: "meilleure-periode-kitesurf-var",
    title: "Quelle est la Meilleure Période pour le Kitesurf dans le Var ?",
    excerpt: "De mars à novembre, le Var offre des conditions exceptionnelles. Analyse mois par mois des meilleures périodes pour pratiquer le kitesurf et le wingfoil.",
    category: "Le Spot",
    date: "2026-01-15",
    readTime: "7 min",
    image: "blog-kitesurf-saut-planche-duotone.jpg",
    alt: "Meilleure période kitesurf Var Hyères - Saison spot Almanarre",
  },
  {
    slug: "choisir-aile-wingfoil-debutant",
    title: "Comment Choisir son Aile de Wingfoil : Guide Débutant",
    excerpt: "Taille, forme, nombre de fenêtres... Tous les critères pour bien choisir votre première aile de wingfoil et progresser rapidement.",
    category: "Wing Foil",
    date: "2026-01-10",
    readTime: "6 min",
    image: "blog-wingfoil-vol-foil-jaune.jpg",
    alt: "Choisir aile wingfoil débutant - Conseil matériel école KiteSurf Passion Hyères",
  },
  {
    slug: "wingfoil-vs-kitesurf-differences",
    title: "Wingfoil vs Kitesurf : Quelles Différences et Lequel Choisir ?",
    excerpt: "Deux disciplines, deux sensations différentes. Comparatif complet pour vous aider à choisir entre le wingfoil et le kitesurf selon votre profil.",
    category: "Wing Foil",
    date: "2025-12-25",
    readTime: "7 min",
    image: "blog-kitesurf-ailes-colorees.jpg",
    alt: "Wingfoil vs kitesurf comparatif - Différences glisse école Hyères Var",
  },
  {
    slug: "technique-pumping-foil-progresser",
    title: "Maîtriser la Technique du Pumping en Foil",
    excerpt: "Le pumping est la clé pour voler sans traction. Découvrez les exercices et conseils pour perfectionner votre technique et gagner en endurance.",
    category: "Pump Foil",
    date: "2025-12-15",
    readTime: "5 min",
    image: "blog-pumpfoil-dock-start-depart.jpg",
    alt: "Technique pumping foil Hyères - Progresser pumpfoil école KiteSurf Passion Var",
  },
  {
    slug: "premiers-vols-wingfoil-conseils",
    title: "Vos Premiers Vols en Wingfoil : 5 Conseils Essentiels",
    excerpt: "Réussir ses premiers décollages en wingfoil demande technique et patience. Voici les 5 conseils clés pour décoller en toute confiance.",
    category: "Wing Foil",
    date: "2025-12-05",
    readTime: "4 min",
    image: "blog-wingfoil-montagnes-maui.jpg",
    alt: "Premiers vols wingfoil conseils - Apprendre wing foil Hyères Almanarre Var",
  },
  {
    slug: "pumpfoil-entrainement-sans-vent",
    title: "Pumpfoil : L'Entraînement Idéal les Jours Sans Vent",
    excerpt: "Transformez les jours sans vent en sessions productives. Le pumpfoil développe votre équilibre et votre cardio tout en vous faisant progresser en foil.",
    category: "Pump Foil",
    date: "2025-11-28",
    readTime: "4 min",
    image: "blog-pumpfoil-rider-plage-duotone.jpg",
  },
  {
    slug: "ecole-kitesurf-hyeres-almanarre-cours",
    title: "École de Kitesurf à Hyères : Découvrez l'Almanarre",
    excerpt: "Cours de kitesurf débutant, location de matériel et spot mythique de l'Almanarre. Découvrez pourquoi Hyères est la destination kitesurf du Var.",
    category: "Kitesurf",
    date: "2025-01-28",
    readTime: "3 min",
    image: "blog-kitesurf-glisse-fille.jpg",
    alt: "École de kitesurf Hyères Almanarre - Cours débutant spot Var KiteSurf Passion",
    featured: true,
  },
  {
    slug: "stage-wingfoil-hyeres-apprendre-voler",
    title: "Stage Wingfoil à Hyères : Apprenez à Voler sur l'Eau",
    excerpt: "Cours de wingfoil débutant à Hyères avec moniteur diplômé. Découvrez le sport tendance sur le spot de l'Almanarre dans le Var.",
    category: "Wing Foil",
    date: "2025-01-27",
    readTime: "3 min",
    image: "blog-wingfoil-vol-eau-cristalline.jpg",
    alt: "Stage wingfoil Hyères Almanarre - Cours débutant école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "pumpfoil-hyeres-dock-start-initiation",
    title: "Pumpfoil à Hyères : Initiez-vous au Dock Start",
    excerpt: "Cours de pumpfoil et dock start à Hyères. Sport sans vent accessible à tous sur la presqu'île de Giens dans le Var.",
    category: "Pump Foil",
    date: "2025-01-26",
    readTime: "3 min",
    image: "blog-pumpfoil-vol-mer-casque.jpg",
    alt: "Pumpfoil dock start Hyères Giens - Initiation foil école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "foil-tracte-hyeres-sensations-vol",
    title: "Foil Tracté à Hyères : Vivez les Sensations du Vol",
    excerpt: "Découvrez le foil tracté par bateau à Hyères. Idéal pour s'initier au vol sans vent sur la baie de Giens dans le Var.",
    category: "Kitesurf",
    date: "2025-01-25",
    readTime: "3 min",
    image: "blog-foil-tracte-bateau-hyeres-vol.jpg",
    alt: "Foil tracté bateau Hyères - Initiation vol école KiteSurf Passion Var",
  },
  {
    slug: "foil-tracte-hyeres-initiation-vol",
    title: "Foil Tracté à Hyères : Initiez-vous au Vol Sans Vent",
    excerpt: "Découvrez le foil tracté par bateau à Hyères sur la baie de Giens. Vivez les sensations du vol au-dessus de l'eau sans dépendre du vent, accessible à tous dès 12 ans.",
    category: "Kitesurf",
    date: "2026-02-02",
    readTime: "9 min",
    image: "blog-foil-tracte-hyeres.jpg",
    alt: "Foil tracté Hyères Giens - Initiation vol bateau école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "wakeboard-hyeres-glisse-nautique",
    title: "Wakeboard à Hyères : La Glisse Nautique Accessible à Tous",
    excerpt: "Découvrez le wakeboard à Hyères sur la baie de Giens. Activité nautique fun et accessible dès 8 ans, encadrée par notre moniteur diplômé.",
    category: "Wakeboard",
    date: "2026-02-01",
    readTime: "8 min",
    image: "blog-wakeboard-hyeres.jpg",
    alt: "Wakeboard Hyères Giens - Glisse nautique école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "location-kitesurf-hyeres-almanarre-guide",
    title: "Location Matériel Kitesurf à Hyères : Guide Complet",
    excerpt: "Louez votre matériel de kitesurf à Hyères sur le spot de l'Almanarre. Ailes, planches, combinaisons : équipement premium Duotone pour riders autonomes.",
    category: "Kitesurf",
    date: "2026-01-31",
    readTime: "7 min",
    image: "blog-location-materiel.jpg",
    alt: "Location matériel kitesurf Hyères Almanarre - Équipement Duotone école Var",
  },
  {
    slug: "kitesurf-autonome-combien-seances",
    title: "Kitesurf : Combien de Séances pour Devenir Autonome ?",
    excerpt: "De la première leçon au waterstart, découvrez les étapes clés et le nombre de séances nécessaires pour naviguer seul en kitesurf à Hyères.",
    category: "Kitesurf",
    date: "2026-03-01",
    readTime: "8 min",
    image: "blog-kitesurf-waterstart.jpg",
    alt: "Progression kitesurf autonomie Hyères - Nombre séances cours école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "kitesurf-enfant-hyeres-age-ideal",
    title: "Kitesurf Enfant à Hyères : À Quel Âge Commencer ?",
    excerpt: "Votre enfant rêve de kitesurf ? Découvrez l'âge idéal, les conditions de sécurité et nos formules adaptées aux juniors à l'Almanarre.",
    category: "Kitesurf",
    date: "2026-02-28",
    readTime: "7 min",
    image: "blog-kitesurf-kitesurfeuse-planche.jpg",
    alt: "Kitesurf enfant Hyères Almanarre - Cours junior école KiteSurf Passion Var",
  },
  {
    slug: "almanarre-meilleur-spot-kitesurf-france",
    title: "L'Almanarre : Pourquoi C'est le Meilleur Spot de Kitesurf en France",
    excerpt: "Vent régulier, eau plate, cadre exceptionnel : découvrez pourquoi le spot de l'Almanarre à Hyères est considéré comme le meilleur de France.",
    category: "Kitesurf",
    date: "2026-02-25",
    readTime: "9 min",
    image: "blog-kitesurf-aile-duotone-evo-lagon.jpg",
    alt: "Almanarre meilleur spot kitesurf France - École Hyères KiteSurf Passion Var",
  },
  {
    slug: "cours-kitesurf-hyeres-guide-complet",
    title: "Cours de Kitesurf à Hyères : Tout ce qu'il Faut Savoir pour se Lancer",
    excerpt: "Vous rêvez de cours de kitesurf à Hyères ? Guide complet : spot, formules, tarifs et conseils pour débuter sur l'Almanarre avec un moniteur diplômé.",
    category: "Kitesurf",
    date: "2026-03-02",
    readTime: "8 min",
    image: "blog-kitesurf-action-eau.jpg",
    alt: "Cours kitesurf Hyères Almanarre - École KiteSurf Passion moniteur diplômé Var",
    featured: true,
  },
  {
    slug: "spot-kitesurf-almanarre-meilleur-var",
    title: "Le Spot de l'Almanarre à Hyères : Pourquoi c'est le Meilleur Spot Kitesurf du Var",
    excerpt: "Vent fiable, eau plate, cadre unique : découvrez pourquoi le spot kitesurf de l'Almanarre à Hyères est la référence incontournable du Var.",
    category: "Le Spot",
    date: "2026-02-27",
    readTime: "9 min",
    image: "blog-kitesurf-freestyle-pink.jpg",
    alt: "Spot kitesurf Almanarre Hyères - Meilleur spot Var école KiteSurf Passion",
  },
  {
    slug: "kitesurf-ou-wingfoil-choisir-hyeres",
    title: "Kitesurf ou Wingfoil : Lequel Choisir pour Débuter à Hyères ?",
    excerpt: "Kitesurf vs wingfoil : comparatif complet pour choisir la discipline idéale selon votre profil. Conseils d'expert depuis l'Almanarre à Hyères.",
    category: "Wing Foil",
    date: "2026-02-22",
    readTime: "8 min",
    image: "blog-wingfoil-saut-vague-duotone-tahiti.jpg",
    alt: "Kitesurf vs wingfoil comparatif Hyères - Choisir discipline école KiteSurf Passion",
  },
  {
    slug: "stage-kitesurf-hyeres-progresser-almanarre",
    title: "Stage Kitesurf à Hyères : Comment Progresser Rapidement sur l'Almanarre ?",
    excerpt: "Stage kitesurf à Hyères : formules intensives, programme jour par jour et conseils pour progresser vite sur le spot de l'Almanarre dans le Var.",
    category: "Kitesurf",
    date: "2026-02-18",
    readTime: "9 min",
    image: "blog-kitesurf-ailes-neo-duotone-mer.jpg",
    alt: "Stage kitesurf Hyères Almanarre - Progresser rapidement école KiteSurf Passion Var",
  },
  {
    slug: "meteo-vent-kitesurf-hyeres-saisons",
    title: "Quand Pratiquer le Kitesurf à Hyères ? Météo, Vents et Meilleures Saisons",
    excerpt: "Mistral, marin, thermique : guide complet de la météo et des vents pour le kitesurf à Hyères. Découvrez les meilleures saisons mois par mois.",
    category: "Le Spot",
    date: "2026-02-15",
    readTime: "8 min",
    image: "blog-kitesurf-plage-rose.jpg",
    alt: "Météo vent kitesurf Hyères - Saisons Mistral Almanarre école KiteSurf Passion",
  },
  {
    slug: "activites-nautiques-hyeres-famille",
    title: "Activités Nautiques à Hyères en Famille : Le Guide Complet",
    excerpt: "Kitesurf, wingfoil, wakeboard, foil tracté : découvrez toutes les activités nautiques à faire en famille à Hyères et sur la presqu'île de Giens.",
    category: "Kitesurf",
    date: "2026-03-10",
    readTime: "8 min",
    image: "blog-activites-nautiques-famille-hyeres.jpg",
    alt: "Activités nautiques famille Hyères Giens - Sports glisse enfants école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "bon-cadeau-kitesurf-wingfoil-hyeres",
    title: "Bon Cadeau Kitesurf et Wingfoil à Hyères : Offrez des Sensations",
    excerpt: "Offrez un bon cadeau kitesurf, wingfoil ou foil tracté à Hyères. Idée cadeau originale pour un anniversaire, Noël ou toute occasion spéciale.",
    category: "Kitesurf",
    date: "2026-03-08",
    readTime: "6 min",
    image: "blog-kitesurf-grab-coloree.jpg",
    alt: "Bon cadeau kitesurf wingfoil Hyères - Idée cadeau école KiteSurf Passion Var",
  },
  {
    slug: "preparation-physique-kitesurf-exercices",
    title: "Préparation Physique pour le Kitesurf : 10 Exercices Essentiels",
    excerpt: "Renforcez votre corps pour le kitesurf avec ces 10 exercices ciblés. Gainage, explosivité et souplesse pour progresser plus vite sur l'eau.",
    category: "Kitesurf",
    date: "2026-03-05",
    readTime: "7 min",
    image: "blog-kitesurf-saut-action.jpg",
    alt: "Préparation physique kitesurf exercices - Entraînement école KiteSurf Passion Hyères",
  },
  {
    slug: "evg-evjf-activite-nautique-hyeres",
    title: "EVG et EVJF à Hyères : Activités Nautiques pour un Enterrement de Vie Mémorable",
    excerpt: "Organisez un EVG ou EVJF inoubliable à Hyères avec des activités nautiques : wakeboard, foil tracté, kitesurf. Sensations fortes garanties.",
    category: "Wakeboard",
    date: "2026-03-06",
    readTime: "6 min",
    image: "blog-wakeboard-evg-evjf.jpg",
    alt: "EVG EVJF activité nautique Hyères - Enterrement vie groupe école KiteSurf Passion",
  },
  {
    slug: "hebergement-kitesurf-hyeres-ou-dormir",
    title: "Où Dormir pour un Séjour Kitesurf à Hyères ? Guide Hébergement",
    excerpt: "Les meilleurs hébergements près du spot de l'Almanarre à Hyères : hôtels, campings, locations. Conseils pratiques pour votre séjour kitesurf.",
    category: "Le Spot",
    date: "2026-03-04",
    readTime: "7 min",
    image: "blog-kitesurf-silhouette-saut-sunset.jpg",
    alt: "Hébergement kitesurf Hyères Almanarre - Où dormir séjour école KiteSurf Passion Var",
  },
  {
    slug: "apprendre-kitesurf-hyeres-guide-debutant",
    title: "Apprendre le Kitesurf à Hyères : Guide Complet pour Débutants",
    excerpt: "Vous voulez apprendre le kitesurf à Hyères ? Découvrez notre guide complet : matériel, sécurité, durée d'apprentissage et pourquoi choisir le spot de l'Almanarre.",
    category: "Kitesurf",
    date: "2025-03-10",
    readTime: "5 min",
    image: "blog-kitesurf-glisse-turquoise.jpg",
    alt: "Apprendre kitesurf Hyères Almanarre - Guide débutant école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "spot-kitesurf-almanarre-hyeres",
    title: "Spot Kitesurf Almanarre Hyères : Tout Savoir sur le Meilleur Spot du Var",
    excerpt: "L'Almanarre à Hyères est le spot kitesurf incontournable de Méditerranée. Vent, conditions, accès, carte : tout ce qu'il faut savoir pour rider.",
    category: "Le Spot",
    date: "2025-02-24",
    readTime: "5 min",
    image: "blog-kitesurf-saut-vagues.jpg",
    alt: "Spot kitesurf Almanarre Hyères Var - Guide complet meilleur spot Méditerranée",
    featured: true,
  },
  {
    slug: "wingfoil-vs-kitesurf-quelle-discipline-choisir",
    title: "Wingfoil vs Kitesurf : Quelle Discipline Choisir à Hyères ?",
    excerpt: "Wingfoil ou kitesurf : laquelle choisir pour débuter à Hyères ? Comparatif complet : matériel, niveau requis, sensations, vent minimum.",
    category: "Wing Foil",
    date: "2025-03-18",
    readTime: "6 min",
    image: "blog-wingfoil-rider-vague-unit-duotone.jpg",
    alt: "Wingfoil vs kitesurf comparatif Hyères - Quelle discipline choisir école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "quand-faire-kitesurf-hyeres-saisons",
    title: "Quand Partir Faire du Kitesurf à Hyères ? Guide Saison par Saison",
    excerpt: "Printemps, été, automne : quelle est la meilleure période pour faire du kitesurf à Hyères ? Analyse des vents, températures et conditions mois par mois sur l'Almanarre.",
    category: "Le Spot",
    date: "2026-03-28",
    readTime: "12 min",
    image: "blog-kitesurf-almanarre-action.jpg",
    alt: "Quand faire kitesurf Hyères saisons - Guide périodes vent Almanarre école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "mistral-vent-est-almanarre-conditions-niveau",
    title: "Mistral ou Vent d'Est à l'Almanarre : Quelles Conditions Selon Votre Niveau ?",
    excerpt: "Mistral side-shore ou vent d'Est on-shore : découvrez quel vent choisir à l'Almanarre selon votre niveau de kitesurf. Analyse experte du spot de Hyères.",
    category: "Le Spot",
    date: "2026-03-25",
    readTime: "11 min",
    image: "blog-kitesurf-strapless-vague-duotone.jpg",
    alt: "Mistral vent Est Almanarre kitesurf conditions - Guide niveau spot Hyères KiteSurf Passion",
    featured: true,
  },
  {
    slug: "stage-kitesurf-hyeres-formule-choisir",
    title: "Stage Kitesurf à Hyères : 5 Jours, Semi-Privé ou Cours Particulier ?",
    excerpt: "Stage 5 jours, cours semi-privé ou leçon particulière : quelle formule de kitesurf choisir à Hyères ? Comparatif complet pour trouver l'option idéale.",
    category: "Kitesurf",
    date: "2026-03-22",
    readTime: "11 min",
    image: "blog-kitesurf-cours-groupe.jpg",
    alt: "Stage kitesurf Hyères formule choisir - Cours particulier semi-privé école KiteSurf Passion",
    featured: true,
  },
  {
    slug: "prix-stage-kitesurf-hyeres",
    title: "Prix d'un stage de kitesurf à Hyères : quel budget prévoir pour débuter ?",
    excerpt: "Combien coûte un stage de kitesurf à Hyères ? Tarifs 2026 par formule, budget séjour complet, écarts entre écoles et conseils pour réserver.",
    category: "Kitesurf",
    date: "2026-05-30",
    readTime: "9 min",
    image: "blog-kitesurf-marche-plage.jpg",
    alt: "Prix stage kitesurf Hyères budget - Tarifs cours école KiteSurf Passion Almanarre",
    featured: true,
  },
  {
    slug: "cours-particulier-ou-collectif-kitesurf-hyeres",
    title: "Cours particulier kitesurf Hyères : que choisir ?",
    excerpt: "Cours particulier kitesurf Hyères ou stage collectif ? Comparez les avantages, les tarifs et les profils pour choisir la bonne formule à l'Almanarre avec Kitesurf Passion.",
    category: "Kitesurf",
    date: "2026-04-01",
    readTime: "10 min",
    image: "blog-cours-particulier-kitesurf.jpg",
    alt: "Cours particulier ou collectif kitesurf Hyères - Comparatif formules école KiteSurf Passion Almanarre",
    featured: true,
  },
  {
    slug: "stage-kitesurf-debutant-hyeres",
    title: "Stage kitesurf débutant à Hyères : le guide pour bien commencer",
    excerpt: "Vous cherchez un stage de kitesurf débutant à Hyères ? Découvrez le programme, le déroulé sur 5 jours, les conditions à l'Almanarre et comment progresser en sécurité.",
    category: "Kitesurf",
    date: "2026-04-03",
    readTime: "10 min",
    image: "blog-kitesurf-cours-individuel.jpg",
    alt: "Stage kitesurf débutant Hyères Almanarre - Programme 5 jours école KiteSurf Passion Var",
    featured: true,
  },
  {
    slug: "stage-kitesurf-hyeres-3-jours-ou-5-jours",
    title: "Stage kitesurf Hyères : 3 jours ou 5 jours ?",
    excerpt: "Vous hésitez entre un stage kitesurf de 3 jours ou 5 jours à Hyères ? Comparez les deux formats selon votre niveau, votre temps disponible et votre objectif de progression.",
    category: "Kitesurf",
    date: "2026-04-04",
    readTime: "10 min",
    image: "blog-kitesurf-spray-turquoise.jpg",
    alt: "Stage kitesurf 3 jours ou 5 jours Hyères - Comparatif durée école KiteSurf Passion Almanarre",
    featured: true,
  },
  {
    slug: "premier-stage-kitesurf-hyeres-checklist",
    title: "Premier stage de kitesurf à Hyères : checklist complète pour débuter sereinement",
    excerpt: "Préparez votre premier stage de kitesurf à Hyères avec la checklist complète : équipement, mental, sécurité, spot de l'Almanarre, déroulé sur 5 jours et conseils débutant.",
    category: "Kitesurf",
    date: "2026-04-06",
    readTime: "12 min",
    image: "blog-kitesurf-preparation.jpg",
    alt: "Premier stage kitesurf Hyères checklist débutant - École KiteSurf Passion Almanarre",
    featured: true,
  },
  {
    slug: "apprendre-kitesurf-40-50-60-ans",
    title: "Apprendre le kitesurf à 40, 50 ou 60 ans à Hyères",
    excerpt: "Oui, il est possible d'apprendre le kitesurf à 40, 50 ou 60 ans à Hyères. Découvrez pourquoi l'Almanarre est un spot idéal, quelle formule choisir et comment progresser en confiance.",
    category: "Kitesurf",
    date: "2026-04-10",
    readTime: "10 min",
    image: "blog-kitesurf-cours-plage.jpg",
    alt: "Apprendre kitesurf adulte 40 50 60 ans Hyères - Stage débutant école KiteSurf Passion Almanarre",
    featured: true,
  },
  {
    slug: "logement-stage-kitesurf-hyeres",
    title: "Où loger pour un stage de kitesurf à Hyères ? Guide logement par zone",
    excerpt: "Almanarre, Giens, port, centre-ville : comparatif complet des zones de logement pour un stage de kitesurf à Hyères. Camping, hôtel presqu'île de Giens, airbnb, accès vélo et logistique pour rejoindre le spot.",
    category: "Le Spot",
    date: "2026-06-02",
    readTime: "11 min",
    image: "blog-logement-stage-kitesurf-hyeres.jpg",
    alt: "Logement stage kitesurf Hyères Almanarre Giens - Guide hébergement école Kitesurf Passion Var",
    featured: true,
  },
];

export type BlogArticle = (typeof blogArticles)[number];
