// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-school-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_school_info_default = defineTool({
  name: "get_school_info",
  title: "Get school info",
  description: "Return public information about Kitesurf Passion: school name, location, contact details, and the disciplines taught.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Kitesurf Passion",
      founded: 1999,
      location: "Carqueiranne / Hy\xE8res (Var), France",
      main_spot: "L'Almanarre, Hy\xE8res",
      website: "https://www.kitesurfpassion.fr",
      phone: "+33 6 72 71 69 05",
      email: "crosyo69@gmail.com",
      siret: "432 262 129 00039",
      disciplines: [
        "Cours de kitesurf",
        "Stage 100% Glisse",
        "Cours \xE0 la Carte (particulier)",
        "Cours Collectifs",
        "Stage wingfoil",
        "Cours pumpfoil / dock-start",
        "Foil tract\xE9",
        "Wakeboard",
        "D\xE9poses en mer",
        "Location de mat\xE9riel"
      ],
      certifications: ["FFVL", "BPJEPS"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-reservations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var ACTIVITY_LABEL = {
  kitesurf: "Kitesurf",
  wingfoil: "Wingfoil",
  pumpfoil: "Pumpfoil",
  foil_tracte: "Foil tract\xE9",
  stage_100_glisse: "Stage 100% Glisse"
};
var SCHEDULE_NOTICE = "Les horaires seront communiqu\xE9s la veille par t\xE9l\xE9phone en fonction des conditions m\xE9t\xE9orologiques.";
function formatDateFR(iso) {
  try {
    const [y, m, d] = iso.split("-").map(Number);
    const dt = new Date(Date.UTC(y, (m ?? 1) - 1, d ?? 1));
    return new Intl.DateTimeFormat("fr-FR", {
      day: "numeric",
      month: "long",
      year: "numeric",
      timeZone: "UTC"
    }).format(dt);
  } catch {
    return iso;
  }
}
var list_my_reservations_default = defineTool2({
  name: "list_my_reservations",
  title: "List my reservations",
  description: "Liste les r\xE9servations Kitesurf Passion de l'utilisateur connect\xE9 : activit\xE9, date, nombre de participants, statut. Les horaires ne sont pas planifi\xE9s \xE0 l'avance : ils sont communiqu\xE9s la veille par t\xE9l\xE9phone selon les conditions m\xE9t\xE9orologiques.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [resvRes, pkgRes] = await Promise.all([
      sb.from("reservations").select(
        `id, participants, skill_level, status, notes, created_at,
           daily_group_id,
           daily_groups ( date, activity )`
      ).eq("user_id", userId).order("created_at", { ascending: false }),
      sb.from("package_bookings").select(
        `id, status, booking_kind, created_at,
           daily_group_id,
           daily_groups ( date, activity ),
           client_packages!inner ( id, user_id, package_code, activity )`
      ).eq("client_packages.user_id", userId).order("created_at", { ascending: false })
    ]);
    if (resvRes.error) {
      return { content: [{ type: "text", text: resvRes.error.message }], isError: true };
    }
    if (pkgRes.error) {
      return { content: [{ type: "text", text: pkgRes.error.message }], isError: true };
    }
    const items = [];
    for (const r of resvRes.data ?? []) {
      const dg = r.daily_groups;
      const date = dg?.date ?? null;
      const activity = dg?.activity ?? "kitesurf";
      items.push({
        id: r.id,
        kind: "reservation",
        activity,
        activity_label: ACTIVITY_LABEL[activity] ?? activity,
        date,
        date_label: date ? formatDateFR(date) : null,
        participants: r.participants ?? 1,
        status: r.status
      });
    }
    for (const b of pkgRes.data ?? []) {
      const dg = b.daily_groups;
      const date = dg?.date ?? null;
      const activity = dg?.activity ?? b.client_packages?.activity ?? "kitesurf";
      items.push({
        id: b.id,
        kind: "package_booking",
        activity,
        activity_label: ACTIVITY_LABEL[activity] ?? activity,
        date,
        date_label: date ? formatDateFR(date) : null,
        participants: 1,
        status: b.status,
        package_code: b.client_packages?.package_code ?? null
      });
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    items.sort((a, b) => {
      const aFuture = (a.date ?? "") >= today;
      const bFuture = (b.date ?? "") >= today;
      if (aFuture !== bFuture) return aFuture ? -1 : 1;
      if (aFuture) return (a.date ?? "").localeCompare(b.date ?? "");
      return (b.date ?? "").localeCompare(a.date ?? "");
    });
    const lines = [];
    if (items.length === 0) {
      lines.push("Aucune r\xE9servation trouv\xE9e pour ce compte.");
    } else {
      lines.push(`${items.length} r\xE9servation(s) :`);
      for (const it of items) {
        const kindLabel = it.kind === "package_booking" ? "Pack" : "R\xE9servation";
        const dateLabel = it.date_label ?? "date inconnue";
        const extra = it.package_code ? ` (code ${it.package_code})` : "";
        lines.push(
          `- ${kindLabel} \u2014 ${it.activity_label} \u2014 ${dateLabel}${extra} \u2014 ${it.participants} participant(s) \u2014 statut ${it.status}`
        );
      }
      lines.push("");
      lines.push(SCHEDULE_NOTICE);
    }
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: {
        reservations: items,
        schedule_notice: SCHEDULE_NOTICE
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "unqxudbxxzzmmbwwxwcr";
var mcp_default = defineMcp({
  name: "kitesurf-passion-mcp",
  title: "Kitesurf Passion",
  version: "0.1.0",
  instructions: "Tools for Kitesurf Passion (\xE9cole de kitesurf & wingfoil \xE0 Hy\xE8res, France). Use `get_school_info` for public school details and `list_my_reservations` to read the signed-in user's bookings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_school_info_default, list_my_reservations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
