// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-school-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_school_info_default = defineTool({
  name: "get_school_info",
  title: "Get school info",
  description: "Return public information about Kitesurf Passion: school name, location, contact details, and the disciplines taught.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Kitesurf Passion",
      founded: 1999,
      location: "Carqueiranne / Hy\xE8res (Var), France",
      main_spot: "L'Almanarre, Hy\xE8res",
      website: "https://www.kitesurfpassion.fr",
      phone: "+33 6 72 71 69 05",
      email: "crosyo69@gmail.com",
      siret: "432 262 129 00039",
      disciplines: [
        "Cours de kitesurf",
        "Stage 100% Glisse",
        "Cours \xE0 la Carte (particulier)",
        "Cours Collectifs",
        "Stage wingfoil",
        "Cours pumpfoil / dock-start",
        "Foil tract\xE9",
        "Wakeboard",
        "D\xE9poses en mer",
        "Location de mat\xE9riel"
      ],
      certifications: ["FFVL", "BPJEPS"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-reservations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_reservations_default = defineTool2({
  name: "list_my_reservations",
  title: "List my reservations",
  description: "List the signed-in user's Kitesurf Passion reservations (id, session, participants, skill level, status, dates).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser(ctx).from("reservations").select(
      "id, participants, skill_level, status, notes, created_at, updated_at, session_id, sessions ( starts_at, ends_at, discipline, location )"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { reservations: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "unqxudbxxzzmmbwwxwcr";
var mcp_default = defineMcp({
  name: "kitesurf-passion-mcp",
  title: "Kitesurf Passion",
  version: "0.1.0",
  instructions: "Tools for Kitesurf Passion (\xE9cole de kitesurf & wingfoil \xE0 Hy\xE8res, France). Use `get_school_info` for public school details and `list_my_reservations` to read the signed-in user's bookings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_school_info_default, list_my_reservations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
